### ISSUE TITLE
Manglende oplysninger på kortet

### ISSUE THREAD

**Issue by Jakobsenp** [kennethfresedk/ha-aula-card#10]
Hej Kenneth
Som aftalt, og tak for et ellers fint kort :)

Pt. så får jeg ikke alle oplysninger vist i kortet.
Jeg har et barn i børnehave, så tænker måske det er det samme som en vuggestue, bort set fra sovetider.

![aula2](https://user-images.githubusercontent.com/79856260/224035260-7a395776-f318-4dab-b299-ea246c5925a4.JPG)
![aula1](https://user-images.githubusercontent.com/79856260/224035264-5d783ce1-d055-40ae-b76a-f52bdca8a555.JPG)

Her er hvad jeg får i sensoren:

![image](https://user-images.githubusercontent.com/79856260/224036628-4b1943be-9234-4b7d-96cc-1ae75261463b.png)

ugeplan: Not available
ugeplan_next: Not available
location: null
sleepIntervals: 
checkInTime: 07:54
checkOutTime: null
activityType: 0
entryTime: 07:50
exitTime: 16:00
exitWith: Poul Jakobsen (Far)
comment: null
spareTimeActivity: null
selfDeciderStartTime: null
selfDeciderEndTime: null
profilePicture: (billedet er med - har blot fjernet den)
icon: mdi:account-school
friendly_name: (Børnehavens navn)

Sig til hvis du har brug for mere.
På forhånd tak

**Comment by kennethfresedk** [comment]
Hej @Jakobsenp.
Min seneste rettelse skulle gerne afhjælpe problemet :)

Prøv at hente den nyeste verison og giv mig gerne en tilbagemelding om det virker.

Se source koden her: 
https://github.com/kennethfresedk/ha-aula-card/pull/11

**Comment by Jakobsenp** [comment]
Hej @kennethfresedk 
Og det gjorde den, det er bare perfekt nu :)

![image](https://user-images.githubusercontent.com/79856260/224251457-1c74f7d6-30b0-43ad-a2a0-7e2950ee22fa.png)

Tak for hurtig afhjælpning. :)
