### ISSUE TITLE
Unable to load picture

### ISSUE THREAD

**Issue by bjerrecs** [kennethfresedk/ha-aula-card#5]
Great card! Just unable to load the picture?
![image](https://user-images.githubusercontent.com/32055984/218096296-be5031c4-2fd7-4fe9-9608-fe43f70d5d09.png)

Here is my folder structure, and I have tried lowercase letters as well.
![image](https://user-images.githubusercontent.com/32055984/218096176-b7767516-14cb-48b3-9084-32ae75dcf43d.png)

I have even changed the
``` 
let imgurl = resp.profilePicture;
``` 
back to
``` 
let imgurl = '/local/aula/picture.jpg'
``` 
without any luck. HA has been restarted multiple times.

**Comment by kennethfresedk** [comment]
Hi @bjerrecs 
If you update to the newest verison of the Aula integraiton v.0.1.31, it will include the picture URL :)
https://github.com/scaarup/aula/releases/tag/v0.1.31

**Comment by kennethfresedk** [comment]
closing issue
