### ISSUE TITLE
Info forsvundet. Samt intet billede

### ISSUE THREAD

**Issue by ghozt1989** [kennethfresedk/ha-aula-card#9]
Jeg kan se efter din seneste update igår er der forsvundet nogle infomationer.

Samt har jeg stadig intet billede fået på er der noget jeg gør forkert?

![image](https://user-images.githubusercontent.com/7705364/218722558-05ade7c3-d346-4ce1-ac16-2ab033c78f7b.png)

**Comment by kennethfresedk** [comment]
@ghozt1989 hvilke informationer får du ud fra din sensor?
Umiddelbart er der ikke noget i koden der skulle breake dette.

De nyeste tilføjelser er kun fejl på manglende data

**Comment by ghozt1989** [comment]
@kennethfresedk 

Dohh.. Lillemor har været inde og rode med aula.. Så nu står der igen hvem der henter :) Beklager fejlen :)

Jeg afventer det med billedet :)
